# -*- coding: utf-8 -*-
"""Summarystatistics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rXSm80AgIaWuEdQ2mBVxZai48ZgEOd_a
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
from pandas import Series, DataFrame 

import scipy 
from scipy import stats 

import numpy as np
import seaborn as sns                       #visualisation
import matplotlib.pyplot as plt             #visualisation
# %matplotlib inline     
sns.set(color_codes=True)

!mkdir sample_data #creating a data folder 
!mkdir sample_data/Happiness.csv #finding a path to the data

# Commented out IPython magic to ensure Python compatibility.
import pylab
import matplotlib.pyplot as plt
# make the plots a little wider by default
# %matplotlib inline
plt.style.use('ggplot')

pylab.rcParams['figure.figsize'] = (10., 8.)

data_path = "sample_data/violentcrimepb.csv"
df = pd.read_csv(data_path,index_col=0)

df.columns = ['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', 'Total']
df= df.drop('2010', 1) 
df= df.drop('Total', 1)
df.head()

df.describe()

"""Uploading and summarising the happiness data """

data_path = "sample_data/Happiness.csv"
Happiness = pd.read_csv(data_path)

Happiness.columns = ['Borough', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']
Happiness.head()

Happiness.describe()

data_path = "sample_data/stops.csv"
stopsearch =  pd.read_csv(data_path, index_col=0)
stopsearch.columns = ['2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018']

stopsearch.head()

stopsearch.describe()

"""Uploading and summarising the data on police force strength """

data_path = "sample_data/officersper1000a.csv"
officersper1000 =  pd.read_csv(data_path)
officersper1000.columns = ['Borough', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018']
officersper1000.head()

officersper1000.describe()

stopsearch.describe()

"""Uploading and summarising the data on income """

data_path = "sample_data/incomes.csv"
incomes =  pd.read_csv(data_path)
incomes.columns = ['Borough', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018']
incomes.head()

incomes.describe()

data_path = "sample_data/pubclub.csv"
pubclub = pd.read_csv(data_path, index_col=0)
pubclub.columns = ['2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018']
pubclub.head()

pubclub.describe()

data_path = "sample_data/stops.csv"
stops =  pd.read_csv(data_path, index_col=0)
stops.columns = ['2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018']
stops.head()

stops.describe()

data_path = "sample_data/pubclub.csv"
pubclub =  pd.read_csv(data_path, index_col=0)
pubclub.columns = ['2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018']
pubclub.head()

pubclub.describe()

from google.colab import drive
drive.mount('/content/drive')